# Generated by Django 5.1.4 on 2025-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de registro"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modificado por"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Moneda")),
                ("code", models.CharField(max_length=4, verbose_name="Código")),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created"], name="core_curren_created_f07b88_idx"
                    )
                ],
            },
        ),
    ]
