# Generated by Django 5.1.4 on 2025-01-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="filters",
            field=models.JSONField(blank=True, null=True, verbose_name="filtros"),
        ),
    ]
