# Generated by Django 5.1.4 on 2025-01-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_currency_filters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="filters",
            field=models.JSONField(blank=True, default=dict, verbose_name="filtros"),
        ),
    ]
