# Generated by Django 5.1.4 on 2025-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_currency_filters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitExpectedMargin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de registro"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modificado por"
                    ),
                ),
                (
                    "porcentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Margen"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created"], name="core_profit_created_319f65_idx"
                    )
                ],
            },
        ),
    ]
