# Generated by Django 5.1.4 on 2025-01-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profitexpectedmargin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(max_length=4, unique=True, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Moneda"),
        ),
    ]
