# Generated by Django 5.1.4 on 2025-01-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_currency_code_alter_currency_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfitExpectedMargin",
            new_name="SelectionCalculationPreferences",
        ),
        migrations.RenameIndex(
            model_name="selectioncalculationpreferences",
            new_name="core_select_created_cfce9e_idx",
            old_name="core_profit_created_319f65_idx",
        ),
    ]
