# Generated by Django 5.1.4 on 2025-01-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_selectioncalculationpreferences_porcentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectioncalculationpreferences",
            name="profitMargin",
            field=models.DecimalField(
                decimal_places=2,
                default=0.04,
                max_digits=6,
                verbose_name="Margen de Ganáncia",
            ),
        ),
    ]
